name: README Update Automation

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    name: Update README after PR merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      # Check out the repo to access its content
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python using the latest stable version
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract PR Number and Commit SHA
        id: extract_info
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMIT_SHA=$(jq --raw-output .pull_request.head.sha "$GITHUB_EVENT_PATH")

          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Display extracted info
        run: |
          echo "Pull Request Number: $PR_NUMBER"
          echo "Commit SHA: $COMMIT_SHA"

      # Extract PR Number and Commit SHA from the GitHub event context

      # Run the Python script
      
      # Additional step to enable debugging, helps in troublshooting
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
          
